---

containers:

  # https://en.wikipedia.org/wiki/Comparison_of_video_container_formats
  videos:
    -
      name:      Microsoft Advanced Systems Format
      supported: true
      transcode: mkv
      exts:
        - asf
        - wma
        - wmv
    -
      name:      DivX Media Format
      supported: true
      transcode: mkv
      exts:
        - divx
    -
      name:      Adobe Flash Video
      supported: true
      transcode: mkv
      exts:
        - flv
        - f4v
    -
      name:      Matroska Multimedia Container
      supported: true
      transcode: null
      exts:
        - mkv
        - mk3d
        - webm
    -
      name:      MPEG-4 Part 14
      supported: true
      transcode: mkv
      exts:
        - mp4
    -
      name:      Moving Picture Experts Group
      supported: true
      transcode: mkv
      exts:
        - mpg
        - mpeg
    -
      name:      Xiph Ogg
      supported: true
      transcode: mkv
      exts:
        - ogv
    -
      name:      Apple QuickTime
      supported: true
      transcode: mkv
      exts:
        - mov
        - qt
    -
      name:      RealMedia Variable Bitrate
      supported: true
      transcode: mkv
      exts:
        - rmvb
    -
      name:      Video Object
      supported: false
      transcode: mkv
      exts:
        - vob
        - ifo
        - bup

  # https://en.wikipedia.org/wiki/Subtitle_(captioning)#Subtitle_formats
  subtitles:

    -
      name     : AQTitle
      supported: true
      exts:
        - aqt
    -
      name     : Gloss Subtitle
      supported: true
      exts:
        - gsub
    -
      name     : JACOSub
      supported: true
      exts:
        - jss
    -
      name     : MicroDVD
      supported: true
      exts:
        - sub
    -
      name     : MPEG-4 Timed Text
      supported: true
      exts:
        - ttxt
    -
      name     : MPSub
      supported: true
      exts:
        - sub
    -
      name     : Phoenix Subtitle
      supported: true
      exts:
        - pjs
    -
      name     : PowerDivX
      supported: true
      exts:
        - psb
    -
      name     : RealText
      supported: true
      exts:
        - rt
    -
      name     : SAMI
      supported: true
      exts:
        - smi
    -
      name     : Spruce Subtitle Format
      supported: true
      exts:
        - sti
    -
      name     : Structured Subtitle Format
      supported: true
      exts:
        - ssf
    -
      name     : SubRip
      supported: true
      exts:
        - srt
    -
      name     : SubStation Alpha
      supported: true
      exts:
        - ssa
        - ass
    -
      name     : SubViewer
      supported: true
      exts:
        - sub
    -
      name     : Universal Subtitle Format
      supported: true
      exts:
        - usf
    -
      name     : Matroska Multimedia Container
      supported: true
      exts:
        - mks

...
