
// general configuration
Config::set('tpl.filepath.tv',      '${seriesname}/Season ${episodeseason}/${seriesname} - S${episodeseason}E${episodenumber}${episodename}.${ext}');
Config::set('tpl.filepath.movie',   '${moviename} [${movieyear}]/${moviename} [${movieyear}] [${movieimdb}].${ext}');
Config::set('dirpath.input',        '/external/media/queue/');
Config::set('dirpath.output',       '/external/media/tv/');
Config::set('files.extensions',     'mp4,mkv,avi,mov,srt');

// runtime configuration
Config::setRuntime('php.timezone',      'America/New_York');
Config::setRuntime('script.verbosity',  1);
Config::setRuntime('script.colors',     true);
Config::setRuntime('script.mode',       'tv');
Config::setRuntime('script.stdout',     fopen('php://stdout', 'w'));
Config::setRuntime('script.stdin',      fopen('php://stdin', 'r'));

