---

##
# This file is part of the `src-run/serferals-media-organizer` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

imports :
    - { resource : 'parameters.yml' }

parameters :

    sr.serferals.name             : "src-run/serferals"
    sr.serferals.version          : "2.1.0"
    sr.serferals.author           : "Rob Frawley 2nd"
    sr.serferals.email            : "rmf@src.run"
    sr.serferals.license          : "MIT License"

    sr.serferals.api_tmdb_key     : %api_tmdb_key%
    sr.serferals.api_tmdb_log     : %api_tmdb_log%

    sr.serferals.ext_media        : %ext_media%
    sr.serferals.ext_remove_pre   : %ext_remove_pre%
    sr.serferals.ext_remove_post  : %ext_remove_post%

    sr.serferals.tpl_path_movie   : "movie/{{ name }}{%% if year is defined %%} ({{ year }}){%% endif %%}/"
    sr.serferals.tpl_file_movie   : "{{ name }}{%% if year is defined %%} ({{ year }}){%% endif %%}{%% if id is defined %%} [{{ id }}]{%% endif %%}.{{ ext }}"
    sr.serferals.tpl_path_episode : "tv/{{ name|raw }}{%% if year is defined %%} ({{ year }}){%% endif %%}/Season {{ season }}/"
    sr.serferals.tpl_file_episode : "{{ name|raw }}{%% if year is defined %%} ({{ year }}){%% endif %%} [S{{ season }}E{{ start }}{%% if end is defined %%}-{{ end }}{%% endif %%}]{%% if title is defined %%} {{ title|raw }}{%% endif %%}.{{ ext }}"

services :

    sr.serferals.application :
        class     : SR\Serferals\Application\SerferalsApplication
        arguments :
            - %sr.serferals.name%
            - %sr.serferals.version%
            - %sr.serferals.author%
            - %sr.serferals.email%
            - %sr.serferals.license%
        calls :
            - [ setContainer, [ "@service_container" ] ]
            - [ add,          [ "@sr.serferals.scan_command" ] ]

    sr.serferals.scan_command :
        class : SR\Serferals\Command\ScanCommand
        arguments :
            - %sr.serferals.ext_media%
            - %sr.serferals.ext_remove_pre%
            - %sr.serferals.ext_remove_post%

    sr.serferals.duplicates_command :
        class : SR\Serferals\Command\DuplicatesCommand

    sr.serferals.filesystem :
        class : Symfony\Component\Filesystem\Filesystem

    sr.serferals.console_logger :
        class     : Symfony\Component\Console\Logger\ConsoleLogger
        arguments :
            - "@sr.serferals.console_output"

    sr.serferals.console_input :
        class : Symfony\Component\Console\Input\ArgvInput

    sr.serferals.console_output :
        class : Symfony\Component\Console\Output\ConsoleOutput

    sr.serferals.console_style :
        class     : SR\Console\Style\Style
        arguments :
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"

    sr.serferals.operation_remove_ext :
        class     : SR\Serferals\Component\Operation\RemoveExtOperation
        arguments :
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls :
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.operation_remove_dir :
        class     : SR\Serferals\Component\Operation\RemoveDirOperation
        arguments :
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls :
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.operation_path_scan :
        class     : SR\Serferals\Component\Operation\PathScanOperation
        arguments :
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls :
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.operation_file_resolver :
        class     : SR\Serferals\Component\Operation\FileResolverOperation
        arguments :
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls :
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.operation_api_lookup :
        class     : SR\Serferals\Component\Operation\ApiLookupOperation
        arguments :
            - "@sr.serferals.operation_file_resolver"
            - "@sr.serferals.tmdb_episode_resolver"
            - "@sr.serferals.tmdb_movie_resolver"
        calls :
            - [ setInput, [ "@sr.serferals.console_input" ] ]
            - [ setOutput, [ "@sr.serferals.console_output" ] ]
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.tmdb_episode_resolver :
        class     : SR\Serferals\Component\Tmdb\EpisodeResolver
        arguments :
            - %sr.serferals.api_tmdb_key%
            - %sr.serferals.api_tmdb_log%
        calls :
            - [ setInput, [ "@sr.serferals.console_input" ] ]
            - [ setOutput, [ "@sr.serferals.console_output" ] ]
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.tmdb_movie_resolver :
        class     : SR\Serferals\Component\Tmdb\MovieResolver
        arguments :
            - %sr.serferals.api_tmdb_key%
            - %sr.serferals.api_tmdb_log%
        calls :
            - [ setInput, [ "@sr.serferals.console_input" ] ]
            - [ setOutput, [ "@sr.serferals.console_output" ] ]
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    sr.serferals.operation_rename :
        class     : SR\Serferals\Component\Operation\RenameOperation
        arguments :
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls :
            - [ setStyle, [ "@sr.serferals.console_style" ] ]
            - [ setFileTemplateEpisode, [ %sr.serferals.tpl_path_episode%, %sr.serferals.tpl_file_episode% ]]
            - [ setFileTemplateMovie, [ %sr.serferals.tpl_path_movie%, %sr.serferals.tpl_file_movie% ]]

...
