---

##
# This file is part of the `src-run/serferals` project.
#
# (c) Rob Frawley 2nd <rmf@src.run>
#
# For the full copyright and license information, view the LICENSE.md
# file distributed with this source code.
##

#
# import additional resources
#
imports:

    - { resource: 'parameters.yml' }


#
# parameter variables
#
parameters:

    sr.serferals.name:                    src-run/serferals
    sr.serferals.version:                 3.0.0
    sr.serferals.author:                  Rob Frawley 2nd
    sr.serferals.email:                   rmf@src.run
    sr.serferals.license:                 MIT License

    sr.serferals.tmdb_api_metadata_key:            %tmdb_api_metadata_key%
    sr.serferals.tmdb_api_metadata_log:            %tmdb_api_metadata_log%

    sr.serferals.extensions_search:       %extensions_search%
    sr.serferals.extensions_remove_first: %extensions_remove_first%
    sr.serferals.extensions_remove_after: %extensions_remove_after%

    sr.serferals.tpl_path_movie:   "movie/{{ name }}{%% if year is defined %%} ({{ year }}){%% endif %%}/"
    sr.serferals.tpl_file_movie:   "{{ name }}{%% if year is defined %%} ({{ year }}){%% endif %%}{%% if id is defined %%} [{{ id }}]{%% endif %%}.{{ ext }}"
    sr.serferals.tpl_path_episode: "tv/{{ name|raw }}{%% if year is defined %%} ({{ year }}){%% endif %%}/Season {{ season }}/"
    sr.serferals.tpl_file_episode: "{{ name|raw }}{%% if year is defined %%} ({{ year }}){%% endif %%} [S{{ season }}E{{ start }}{%% if end is defined %%}-{{ end }}{%% endif %%}]{%% if title is defined %%} {{ title|raw }}{%% endif %%}.{{ ext }}"


#
# service definitions
#
services:

    # main application
    sr.serferals.application:
        class: SR\Serferals\Application\SerferalsApplication
        arguments:
            - %sr.serferals.name%
            - %sr.serferals.version%
            - %sr.serferals.author%
            - %sr.serferals.email%
            - %sr.serferals.license%
        calls:
            - [ setContainer, [ "@service_container" ] ]
            - [ add,          [ "@sr.serferals.command.file_organizer" ] ]
            - [ add,          [ "@sr.serferals.command.file_deduplicator" ] ]

    # organizer command
    sr.serferals.command.file_organizer:
        class: SR\Serferals\Command\FileOrganizerCommand
        arguments:
            - %default_destination_path%
        calls:
            - [ setContainersManager, [ "@sr.serferals.manager.containers" ] ]
            - [ setRemoveExtensions,  [ %extensions_remove_first%, %extensions_remove_after% ]]
            - [ setInputOutput,       [ "@sr.serferals.console_io" ] ]
            - [ setFinderGenerator,   [ "@sr.serferals.tasks.finder_generator" ] ]
            - [ setFileMetadata,      [ "@sr.serferals.tasks.file_metadata" ] ]
            - [ setTmdbMetadata,      [ "@sr.serferals.tasks.tmdb_metadata" ] ]
            - [ setExtensionRemover,  [ "@sr.serferals.tasks.extension_remover" ] ]
            - [ setDirectoryRemover,  [ "@sr.serferals.tasks.directory_remover" ] ]
            - [ setFileInstruction,   [ "@sr.serferals.tasks.file_instruction" ] ]
            - [ setFileAtomicMover,   [ "@sr.serferals.tasks.file_atomic_mover" ] ]

    # file format containers manager
    sr.serferals.manager.containers:
        class: SR\Serferals\Component\Format\ContainersManager
        arguments:
            - %container_configurations%

    # deduplicator command
    sr.serferals.command.file_deduplicator:
        class: SR\Serferals\Command\FileDeduplicatorCommand

    # filesystem instance
    sr.serferals.filesystem:
        class: Symfony\Component\Filesystem\Filesystem

    # console logger instance
    sr.serferals.console_logger:
        class: Symfony\Component\Console\Logger\ConsoleLogger
        arguments:
            - "@sr.serferals.console_output"

    # console input instance
    sr.serferals.console_input:
        class: Symfony\Component\Console\Input\ArgvInput

    # console output instance
    sr.serferals.console_output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    # console style instance
    sr.serferals.console_style:
        class: SR\Console\Style\Style
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"

    # console input/output instance
    sr.serferals.console_io:
        class: SR\Serferals\Component\Console\InputOutput
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
            - "@sr.serferals.console_style"

    # file finder generator task
    sr.serferals.tasks.finder_generator:
        class: SR\Serferals\Component\Tasks\Filesystem\FinderGeneratorTask
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls:
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    # file metadata task
    sr.serferals.tasks.file_metadata:
        class: SR\Serferals\Component\Tasks\Metadata\FileMetadataTask
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls:
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    # tmdb metadata task
    sr.serferals.tasks.tmdb_metadata:
        class: SR\Serferals\Component\Tasks\Metadata\TmdbMetadataTask
        arguments:
            - "@sr.serferals.tasks.file_metadata"
            - "@sr.serferals.tmdb.episode"
            - "@sr.serferals.tmdb.movie"
        calls:
            - [ setInput,  [ "@sr.serferals.console_input" ] ]
            - [ setOutput, [ "@sr.serferals.console_output" ] ]
            - [ setStyle,  [ "@sr.serferals.console_style" ] ]

    # extension remover task
    sr.serferals.tasks.extension_remover:
        class: SR\Serferals\Component\Tasks\Filesystem\ExtensionRemoverTask
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls:
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    # directory remover task
    sr.serferals.tasks.directory_remover:
        class: SR\Serferals\Component\Tasks\Filesystem\DirectoryRemoverTask
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls:
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    # file organizer task
    sr.serferals.tasks.file_instruction:
        class: SR\Serferals\Component\Tasks\Filesystem\FileInstructionTask
        calls:
            - [ setFileTemplateEpisode, [ %sr.serferals.tpl_path_episode%, %sr.serferals.tpl_file_episode% ]]
            - [ setFileTemplateMovie,   [ %sr.serferals.tpl_path_movie%, %sr.serferals.tpl_file_movie% ]]

    # atomic file mover task
    sr.serferals.tasks.file_atomic_mover:
        class: SR\Serferals\Component\Tasks\Filesystem\FileAtomicMoverTask
        arguments:
            - "@sr.serferals.console_input"
            - "@sr.serferals.console_output"
        calls:
            - [ setStyle, [ "@sr.serferals.console_style" ] ]

    # episode tmdb resolver
    sr.serferals.tmdb.episode:
        class: SR\Serferals\Component\Tmdb\EpisodeResolver
        arguments:
            - %sr.serferals.tmdb_api_metadata_key%
            - %sr.serferals.tmdb_api_metadata_log%
        calls:
            - [ setInput,  [ "@sr.serferals.console_input" ] ]
            - [ setOutput, [ "@sr.serferals.console_output" ] ]
            - [ setStyle,  [ "@sr.serferals.console_style" ] ]

    # movie tmdb resolver
    sr.serferals.tmdb.movie:
        class: SR\Serferals\Component\Tmdb\MovieResolver
        arguments:
            - %sr.serferals.tmdb_api_metadata_key%
            - %sr.serferals.tmdb_api_metadata_log%
        calls:
            - [ setInput,  [ "@sr.serferals.console_input" ] ]
            - [ setOutput, [ "@sr.serferals.console_output" ] ]
            - [ setStyle,  [ "@sr.serferals.console_style" ] ]

...
