---

imports :
    - { resource : 'parameters.yml' }

parameters :

    rmf.serferals.name    : "Serferals"
    rmf.serferals.version : "2.0.0"
    tpl_path_movie        : "{{ name }}{%% if year is defined %%} ({{ year }}){%% endif %%}/"
    tpl_file_movie        : "{{ name }}{%% if year is defined %%} ({{ year }}){%% endif %%}{%% if id is defined %%} [{{ id }}]{%% endif %%}.{{ ext }}"
    tpl_path_episode      : "{{ name|raw }}{%% if year is defined %%} ({{ year }}){%% endif %%}/Season {{ season }}/"
    tpl_file_episode      : "{{ name|raw }}{%% if year is defined %%} ({{ year }}){%% endif %%} [S{{ season }}E{{ start }}{%% if end is defined %%}-{{ end }}{%% endif %%}]{%% if title is defined %%} {{ title|raw }}{%% endif %%}.{{ ext }}"

services :

    rmf.serferals.application :
        class     : RMF\Serferals\Application\SerferalsApplication
        arguments :
            - "%rmf.serferals.name%"
            - "%rmf.serferals.version%"
        calls :
            - [ setContainer, [ "@service_container" ] ]
            - [ add, [ "@rmf.serferals.scan_command" ] ]
            - [ add, [ "@rmf.serferals.duplicates_command" ] ]

    rmf.serferals.scan_command :
        class : RMF\Serferals\Command\ScanCommand

    rmf.serferals.duplicates_command :
        class : RMF\Serferals\Command\DuplicatesCommand

    rmf.serferals.filesystem :
        class : Symfony\Component\Filesystem\Filesystem

    rmf.serferals.console_logger :
        class     : Symfony\Component\Console\Logger\ConsoleLogger
        arguments :
            - "@rmf.serferals.console_output"

    rmf.serferals.console_input :
        class : Symfony\Component\Console\Input\ArgvInput

    rmf.serferals.console_output :
        class : Symfony\Component\Console\Output\ConsoleOutput

    rmf.serferals.console_style :
        class     : RMF\Serferals\Component\Console\Style\SrcRunStyle
        arguments :
            - "@rmf.serferals.console_input"
            - "@rmf.serferals.console_output"

    rmf.serferals.operation_remove_exts :
        class     : RMF\Serferals\Component\Operation\RemoveExtsOperation
        arguments :
            - "@rmf.serferals.console_input"
            - "@rmf.serferals.console_output"
        calls :
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]

    rmf.serferals.operation_path_scan :
        class     : RMF\Serferals\Component\Operation\PathScanOperation
        arguments :
            - "@rmf.serferals.console_input"
            - "@rmf.serferals.console_output"
        calls :
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]

    rmf.serferals.operation_file_resolver :
        class     : RMF\Serferals\Component\Operation\FileResolverOperation
        arguments :
            - "@rmf.serferals.console_input"
            - "@rmf.serferals.console_output"
        calls :
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]

    rmf.serferals.operation_api_lookup :
        class     : RMF\Serferals\Component\Operation\ApiLookupOperation
        arguments :
            - "@rmf.serferals.operation_file_resolver"
            - "@rmf.serferals.tmdb_episode_resolver"
            - "@rmf.serferals.tmdb_movie_resolver"
        calls :
            - [ setInput, [ "@rmf.serferals.console_input" ] ]
            - [ setOutput, [ "@rmf.serferals.console_output" ] ]
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]

    rmf.serferals.tmdb_episode_resolver :
        class     : RMF\Serferals\Component\Tmdb\EpisodeResolver
        arguments :
            - "%tmdb_api_key%"
            - "%tmdb_api_log%"
        calls :
            - [ setInput, [ "@rmf.serferals.console_input" ] ]
            - [ setOutput, [ "@rmf.serferals.console_output" ] ]
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]

    rmf.serferals.tmdb_movie_resolver :
        class     : RMF\Serferals\Component\Tmdb\MovieResolver
        arguments :
            - "%tmdb_api_key%"
            - "%tmdb_api_log%"
        calls :
            - [ setInput, [ "@rmf.serferals.console_input" ] ]
            - [ setOutput, [ "@rmf.serferals.console_output" ] ]
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]

    rmf.serferals.operation_renamer :
        class     : RMF\Serferals\Component\Operation\RenamerOperation
        arguments :
            - "@rmf.serferals.console_input"
            - "@rmf.serferals.console_output"
        calls :
            - [ setStyle, [ "@rmf.serferals.console_style" ] ]
            - [ setFileTemplateEpisode, [ '%tpl_path_episode%', '%tpl_file_episode%' ]]
            - [ setFileTemplateMovie, [ '%tpl_path_movie%', '%tpl_file_movie%' ]]

...